### ISSUE TITLE
Prepare for nird migration

### ISSUE THREAD

**Issue by knl88** [SeaBee-no/documentation#13]
According to the [migration guide](https://documentation.sigma2.no/files_storage/nird/migration.html) we should try to prepare for migration. For our case I think it should mostly mean deleting all the data ;)

**Comment by JamesSample** [comment]
Closing this for now, as I don't think we can wait for NIRD to migrate before we start further development. I assume they will either migrate everything as it is, or complain and tell use to delete stuff.
