### ISSUE TITLE
Example API upload of geotiffs to geoserver

### ISSUE THREAD

**Issue by knl88** [SeaBee-no/documentation#17]
We can create an example of programmatic geotiff upload to geoserver and geonode refresh. This can be done using the [import api](https://doc-geonode.readthedocs.io/en/latest/005_dev_workshop/006_geonode_apis/importer/rest_examples.html), we should also perhaps look at the [version 2 api](https://geonode.seabee.sigma2.no/api/v2/uploads?format=api).

**Comment by JamesSample** [comment]
See also the links [here](https://github.com/SeaBee-no/workflow_examples#seabee-workflow_examples).
