### ISSUE TITLE
Geovisualisation - Select your area of interest

### ISSUE THREAD

**Issue by deviirmr** [SeaBee-no/documentation#33]
A selection tool (in addition to the zooming function) to select your area of interest (within a square or other polygon)
requested by @HegeGundersen

**Comment by deviirmr** [comment]
@HegeGundersen: could you explain a bit, 
Do you mean the user can draw a polygon on the map and all the icons under the polygon will selected and also on the list in the left panel?

**Comment by HegeGundersen** [comment]
Yes, that is what I was thinking

**Comment by deviirmr** [comment]
The map icon and table row selected based on the area drawn on the map has been implemented.
https://geonode.seabee.sigma2.no/droneViz/
![image](https://github.com/SeaBee-no/documentation/assets/10088434/cc718d05-6038-49e2-8c2d-cad587031fec)

1. Users can select a polygon/rectangle icon from the map (top right corner polygon/rectangle icon) to draw an area on the map.

2. By double-clicking while drawing the polygon will stop the editing.

3. Once the editing stops, the automatic point under the drawn area will be highlighted and the related table row will also highlighted at the same time

4. To clear the currently selected icons on the map and deselect the table row can be done by clicking the clear button(top right corner eraser icon).

@JamesSample

**Comment by JamesSample** [comment]
Nice @deviirmr!

If I draw a shape to select some missions, but then zoom in or out, the points remain selected in the map window, but not in the mission list in the sidebar. Can we keep the missions selected in both the map and the sidebar until the user clicks the "clear" button?

Thanks!

**Comment by HegeGundersen** [comment]
Thanks a lot Deb - nice! And agree to James comment re. selection both in the map and the sidebar.

**Comment by HegeGundersen** [comment]
Also, if ease, could Escape do the same as the eraser (I would have tried that one first, if I didn't knew about the eraser)?

**Comment by HegeGundersen** [comment]
One more thing (should probably be in a separate issue, but I don't know if I'm "allowed" to create new issues): It would be very useful if the user could show/overlay more than one map at a time? And sort the order of them (for instance the polygon "region of interest" on top of a drone image). Would that be possible do you think?

**Comment by deviirmr** [comment]
> Nice @deviirmr!
> 
> If I draw a shape to select some missions, but then zoom in or out, the points remain selected in the map window, but not in the mission list in the sidebar. Can we keep the missions selected in both the map and the sidebar until the user clicks the "clear" button?
> 
> Thanks!

ok, it is just implimeted.

**Comment by deviirmr** [comment]
> Even one more thing: I think polygons should have transparent filling (or perhaps a light colored still transparent fill), with a colored outline.

This is possible, I will fix it

**Comment by deviirmr** [comment]
> One more thing (should probably be in a separate issue, but I don't know if I'm "allowed" to create new issues): It would be very useful if the user could show/overlay more than one map at a time? And sort the order of them (for instance the polygon "region of interest" on top of a drone image). Would that be possible do you think?

This will be a diffrent approch, I will move to a new issue and tag you.

**Comment by deviirmr** [comment]
> Also, if easy, could Escape do the same as the eraser (I would have tried that one first, if I didn't knew about the eraser)?

This is quite true for desktop applications, but I will try for web apps and let you know.

**Comment by deviirmr** [comment]
> > Also, if easy, could Escape do the same as the eraser (I would have tried that one first, if I didn't knew about the eraser)?
> 
> This is quite true for desktop applications, but I will try for web apps and let you know.

It implemented, the user can press the escape key from the keyboard to clear the current selection.

**Comment by deviirmr** [comment]
All the feedback in this thread is implemented except [multi-layer add feature  ](https://github.com/SeaBee-no/documentation/issues/37#issue-1911311434) which I moved to the new issue. So I am closing this issue.
