### ISSUE TITLE
Geovisualisation - link between the selected layer on the map

### ISSUE THREAD

**Issue by deviirmr** [SeaBee-no/documentation#34]
Some kind of link between the selected layer on the map and the list to the left, so that when you click on a SeaBee icon for one of the layers, the same layer gets highlighted in the list. 
requested by @HegeGundersen

**Comment by deviirmr** [comment]
The map icon has been liked to the data list 
![image](https://github.com/SeaBee-no/documentation/assets/10088434/9d2b8efe-293b-4baa-a589-f3ec118ae533)
 by clicking on the map icon will select the row from the list.

@JamesSample

**Comment by HegeGundersen** [comment]
Very nice!
