### ISSUE TITLE
Geovisualisation -  link directly to a certain geographical area and selected

### ISSUE THREAD

**Issue by deviirmr** [SeaBee-no/documentation#35]
Able to customize a link that sends us directly to a certain geographical area and selected layers/maps. I have added Lorna to this email, so she can follow/comment.
requested by @HegeGundersen

**Comment by Lorna-grida** [comment]
As a non-scientific user, I need to filter dataset results by application (eg habitats, seabirds, seals etc) so I can see which datasets have been collected for which application.

**Comment by HegeGundersen** [comment]
Nice, thank you!

**Comment by deviirmr** [comment]
I am closing this request now, but if there is any issue we will open it again.
