### ISSUE TITLE
 Geovisualisation -Filter dataset results by application

### ISSUE THREAD

**Issue by deviirmr** [SeaBee-no/documentation#36]
As a non-scientific user, I need to filter dataset results by application (eg habitats, seabirds, seals etc) so I can see which datasets have been collected for which application.
requested by @Lorna-grida

**Comment by JamesSample** [comment]
Note that the current spec. for `config.yaml` includes a `Theme` attribute (see [here](https://seabee-no.github.io/documentation/data-upload.html#sec-config-file)). For datasets that are processed automatically (currently only the recent seabird surveys), this attribute is also published automatically to Geonode on the dataset page. For example:

![image](https://github.com/SeaBee-no/documentation/assets/12967176/8c9037d4-76b5-49cb-afd6-c83fb8c78678)

So the information needed for this filter will be available (but it's not complete for all datasets at present).

**Comment by deviirmr** [comment]
I was also thinking about picking that "Theme" attribute to filter out the dataset.  Perhaps we will wait until we have at least two or more theme labels in the database.

**Comment by deviirmr** [comment]
@JamesSample: This time we have two themes '**Seabirds**' and '**Habitat**', maybe it's a good starting point for map filter functionality  implementation. 
Those layers don't have any assigned theme I will put them in '**Other**' category.

**Comment by deviirmr** [comment]
its done
![image](https://github.com/SeaBee-no/documentation/assets/10088434/b3e86120-3244-4770-86ea-cefc18b21089)
