### ISSUE TITLE
Switching geonode interface with geoviz page as a landing page

### ISSUE THREAD

**Issue by deviirmr** [SeaBee-no/documentation#38]
In connection with the Seabee annual meeting 2023 and the suggestion, the group has decided that the Geoviz map interface will be the main landing page for the Seabee data portal/GeoNode.
@JamesSample @knl88

**Comment by knl88** [comment]
Interpreted it as https://seabee.no should link to droneviz instead of the default geonode page, that also saves us modifying geonode, perhaps grid just can update the seabee page with 

```html 
<a class="elementor-sub-item elementor-item-anchor" href="https://geonode.seabee.sigma2.no/droneViz/">Geo-Visualization Portal</a>
```

**Comment by deviirmr** [comment]
@JamesSample do you communicate to GRID about the URL or should I do it?

**Comment by JamesSample** [comment]
I can do it.

**Comment by deviirmr** [comment]
I found the solution, now it's possible to configure the Django URL.
I have changed the home/default URL to Geoviz which means that https://geonode.seabee.sigma2.no/ will directly open the  Geoviz page.

**Comment by deviirmr** [comment]
its done.
