### ISSUE TITLE
Explore intermediate options for annotation

### ISSUE THREAD

**Issue by knl88** [SeaBee-no/documentation#7]
Add SeaBee’s GeoServer as a data source in desktop GIS. Explore ArcGIS Pro as a tool for annotation. Explore options for saving digitised polygons back to Sigma2 (e.g. WFST)

**Comment by JamesSample** [comment]
Closing for now as I think we've settled on ArcGIS Pro. I'll open separate issue regarding (i) Exposing mosaics as WMSs from GeoServer, and (ii) annotation possibilities via GeoNode, which might be relevant to the object identification workflow.
